'use strict';

const { VERSION, baseAttributes, color, vec3 } = require('./schema');

function mapType(op, className) {
  if (op === 'ensureFolder' || className === 'Folder') return 'folder';
  if (op === 'createModel' || className === 'Model') return 'model';
  if (op === 'createPart' || className === 'Part' || className === 'MeshPart') return 'part';
  return 'createInstance';
}

function operation(op, className, path, role, properties = {}, context = {}) {
  const goal = context.goal || '';
  return {
    op,
    type: mapType(op, className),
    className,
    path,
    role,
    reason: context.reason || `${role} generated by V89 Detail Compiler.`,
    properties,
    attributes: baseAttributes(role, goal, context.attributes || {}),
    rollback: { action: 'deleteIfCodexGenerated', path },
    verify: { action: 'existsWithAttributes', path, attributes: { CodexGenerated: true, CodexSystem: 'DetailCompiler' } },
    budgetCost: context.budgetCost || 1,
    version: VERSION,
  };
}

function folder(path, role, context = {}) {
  return operation('ensureFolder', 'Folder', path, role || 'folder', {}, { ...context, budgetCost: 0 });
}

function model(path, role, context = {}) {
  return operation('createModel', 'Model', path, role || 'model', {}, { ...context, budgetCost: 0 });
}

function part(path, role, properties = {}, context = {}) {
  const partProperties = {
    Anchored: true,
    CanCollide: properties.CanCollide ?? false,
    Transparency: properties.Transparency ?? 0,
    Material: properties.Material || 'SmoothPlastic',
    Color: properties.Color || color(0.25, 0.2, 0.35),
    Size: properties.Size || vec3(4, 1, 4),
    ...properties,
  };
  if (!properties.CFrame) delete partProperties.CFrame;
  return operation('createPart', 'Part', path, role, partProperties, context);
}

function neon(path, role, size, tint, context = {}) {
  return part(path, role, {
    Material: 'Neon',
    Color: tint || color(0.55, 0.1, 1),
    Size: size || vec3(1, 1, 1),
    Transparency: 0.15,
    CanCollide: false,
  }, { ...context, budgetCost: context.budgetCost || 2 });
}

function transparentProxy(path, role, size, context = {}) {
  return part(path, role, {
    Material: 'ForceField',
    Color: color(0.2, 1, 1),
    Size: size || vec3(6, 6, 1),
    Transparency: 0.92,
    CanCollide: true,
  }, { ...context, budgetCost: context.budgetCost || 1 });
}

function attachment(path, role, context = {}) {
  return operation('createAttachment', 'Attachment', path, role, {}, context);
}

function light(path, role, className, properties = {}, context = {}) {
  return operation('createLight', className || 'PointLight', path, role, {
    Brightness: properties.Brightness ?? 1.5,
    Range: properties.Range ?? 18,
    Color: properties.Color || color(0.55, 0.2, 1),
    Shadows: properties.Shadows ?? true,
    ...properties,
  }, { ...context, budgetCost: context.budgetCost || 2 });
}

function stringValue(path, role, value, context = {}) {
  return operation('createManifestValue', 'StringValue', path, role, {
    Value: String(value == null ? '' : value).slice(0, 199000),
  }, { ...context, budgetCost: 0 });
}

function prompt(path, role, properties = {}, context = {}) {
  return operation('createPrompt', 'ProximityPrompt', path, role, {
    ActionText: properties.ActionText || 'Inspect',
    ObjectText: properties.ObjectText || 'Codex Detail',
    HoldDuration: properties.HoldDuration ?? 0,
    MaxActivationDistance: properties.MaxActivationDistance ?? 12,
    ...properties,
  }, context);
}

function sound(path, role, context = {}) {
  return operation('createSoundPlaceholder', 'Sound', path, role, {
    Name: 'CodexSoundCue',
    Volume: 0.35,
    Looped: false,
  }, context);
}

function particle(path, role, context = {}) {
  return operation('createParticlePlaceholder', 'ParticleEmitter', path, role, {
    Enabled: false,
    Rate: 0,
  }, context);
}

module.exports = {
  attachment,
  folder,
  light,
  model,
  neon,
  operation,
  part,
  particle,
  prompt,
  sound,
  stringValue,
  transparentProxy,
};
