'use strict';

const VERSION = '0.93.0';

const ROOTS = {
  workspace: 'Workspace.CodexProduction.ArchitectureCompiler',
  replicatedStorage: 'ReplicatedStorage.CodexArchitecture',
  premiumMirror: 'ReplicatedStorage.CodexPremiumDirector.Architecture',
  executionMirror: 'ReplicatedStorage.CodexExecutionKernel.Architecture',
};

const CAPABILITIES = [
  'silhouetteGrammar',
  'modularWallGrid',
  'archAndPortalGrammar',
  'roofGrammar',
  'windowDoorGrammar',
  'pillarGrammar',
  'stairGrammar',
  'interiorModules',
  'trimSystems',
  'depthLayering',
  'variantGeneration',
  'mobileBudget',
  'executionKernelBridge',
  'detailCompilerIntegration',
  'reconstructionIntegration',
  'worldcompileIntegration',
  'fidelityIntegration',
];

const SAFETY = {
  codexOwnedOnly: true,
  manualRequiredForRealMeshes: true,
  executionRequiresV72: true,
  mobileBudgetAware: true,
  noPublishUploadMarketplaceDataStoreEconomy: true,
  noFakeMeshTexturePbrAssetIds: true,
};

const AUDIT_KEYS = [
  'silhouetteStrength',
  'modularConsistency',
  'archQuality',
  'wallRhythm',
  'depthLayering',
  'trimDiscipline',
  'roofReadability',
  'doorWindowQuality',
  'interiorReadability',
  'collisionClarity',
  'mobileBudgetSafety',
  'premiumArchitectureFeel',
];

const POLISH_STAGES = [
  'improve silhouette',
  'improve arch proportions',
  'improve wall rhythm',
  'improve depth layering',
  'improve trim discipline',
  'improve window/door frames',
  'improve pillar grammar',
  'improve roof/upper silhouette',
  'improve interior flow',
  'mobile simplification',
  'rerun detail/fidelity/visual/QA',
];

function nowIso() {
  return new Date().toISOString();
}

function safeGoal(goal) {
  return String(goal || '').trim().replace(/\s+/g, ' ') || 'premium modular Roblox architecture';
}

function slugify(value, fallback = 'architecture') {
  const slug = safeGoal(value)
    .replace(/[^0-9A-Za-z]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 58);
  return slug || fallback;
}

function clampScore(value) {
  const number = Number(value);
  return Math.max(0, Math.min(100, Math.round(Number.isFinite(number) ? number : 0)));
}

function vec3(x, y, z) {
  return { x, y, z };
}

function color(r, g, b) {
  return { r, g, b };
}

function baseAttributes(role, goal, extra = {}) {
  return {
    CodexGenerated: true,
    CodexSystem: 'ArchitectureCompiler',
    CodexVersion: VERSION,
    CodexGoal: safeGoal(goal),
    CodexArchitectureRole: role || 'architecture',
    ...extra,
  };
}

function architectureBasePath(goal, suffix = 'Preview') {
  return `${ROOTS.workspace}.${slugify(goal, 'architecture')}_${suffix}`;
}

function mapType(op, className) {
  if (op === 'ensureFolder' || className === 'Folder') return 'folder';
  if (op === 'createModel' || className === 'Model') return 'model';
  if (op === 'createPart' || className === 'Part' || className === 'MeshPart') return 'part';
  return 'createInstance';
}

function operation(op, className, path, role, properties = {}, context = {}) {
  const goal = context.goal || '';
  return {
    op,
    type: mapType(op, className),
    className,
    path,
    role,
    reason: context.reason || `${role} generated by V91 Architecture Compiler.`,
    properties,
    attributes: baseAttributes(role, goal, context.attributes || {}),
    rollback: { action: 'deleteIfCodexGenerated', path },
    verify: { action: 'existsWithAttributes', path, attributes: { CodexGenerated: true, CodexSystem: 'ArchitectureCompiler' } },
    budgetCost: context.budgetCost || 1,
    version: VERSION,
  };
}

function folder(path, role, context = {}) {
  return operation('ensureFolder', 'Folder', path, role || 'folder', {}, { ...context, budgetCost: 0 });
}

function model(path, role, context = {}) {
  return operation('createModel', 'Model', path, role || 'model', {}, { ...context, budgetCost: 0 });
}

function part(path, role, properties = {}, context = {}) {
  return operation('createPart', 'Part', path, role, {
    Anchored: true,
    CanCollide: properties.CanCollide ?? false,
    Transparency: properties.Transparency ?? 0,
    Material: properties.Material || 'SmoothPlastic',
    Color: properties.Color || color(0.2, 0.16, 0.26),
    Size: properties.Size || vec3(4, 1, 4),
    ...properties,
  }, context);
}

function attachment(path, role, context = {}) {
  return operation('createAttachment', 'Attachment', path, role, {}, context);
}

function light(path, role, properties = {}, context = {}) {
  return operation('createLight', 'PointLight', path, role, {
    Brightness: properties.Brightness ?? 1.4,
    Range: properties.Range ?? 18,
    Color: properties.Color || color(0.55, 0.2, 1),
    Shadows: properties.Shadows ?? true,
    ...properties,
  }, { ...context, budgetCost: context.budgetCost || 2 });
}

function prompt(path, role, properties = {}, context = {}) {
  return operation('createPrompt', 'ProximityPrompt', path, role, {
    ActionText: properties.ActionText || 'Inspect',
    ObjectText: properties.ObjectText || 'Architecture',
    HoldDuration: properties.HoldDuration ?? 0,
    MaxActivationDistance: properties.MaxActivationDistance ?? 12,
    ...properties,
  }, context);
}

function billboard(path, role, text, context = {}) {
  return operation('createBillboard', 'BillboardGui', path, role, {
    Enabled: true,
    Size: vec3(5, 1.5, 0),
    StudsOffset: vec3(0, 4, 0),
    Text: text || 'Architecture',
  }, context);
}

function stringValue(path, role, value, context = {}) {
  return operation('createManifestValue', 'StringValue', path, role, {
    Value: String(value == null ? '' : value).slice(0, 199000),
  }, { ...context, budgetCost: 0 });
}

module.exports = {
  VERSION,
  ROOTS,
  CAPABILITIES,
  SAFETY,
  AUDIT_KEYS,
  POLISH_STAGES,
  architectureBasePath,
  attachment,
  baseAttributes,
  billboard,
  clampScore,
  color,
  folder,
  light,
  model,
  nowIso,
  operation,
  part,
  prompt,
  safeGoal,
  slugify,
  stringValue,
  vec3,
};
