return {
	Order = { "Normal", "Big", "Golden", "Rainbow", "VoidTouched" },
	Normal = {
		DisplayName = "Normal",
		Weight = 76,
		ValueMultiplier = 1,
		VoidMultiplier = 1,
		Scale = 1,
		Color = nil,
		Material = Enum.Material.SmoothPlastic,
	},
	Big = {
		DisplayName = "Big",
		Weight = 14,
		ValueMultiplier = 1.45,
		VoidMultiplier = 1.25,
		Scale = 1.35,
		Color = nil,
		Material = Enum.Material.SmoothPlastic,
	},
	Golden = {
		DisplayName = "Golden",
		Weight = 6,
		ValueMultiplier = 2.5,
		VoidMultiplier = 1.75,
		Scale = 1.1,
		Color = Color3.fromRGB(255, 205, 76),
		Material = Enum.Material.Metal,
	},
	Rainbow = {
		DisplayName = "Rainbow",
		Weight = 3,
		ValueMultiplier = 4,
		VoidMultiplier = 3,
		Scale = 1.15,
		Color = Color3.fromRGB(255, 92, 225),
		Material = Enum.Material.Neon,
	},
	VoidTouched = {
		DisplayName = "Void Touched",
		Weight = 1,
		ValueMultiplier = 6,
		VoidMultiplier = 5,
		Scale = 1.25,
		Color = Color3.fromRGB(78, 35, 130),
		Material = Enum.Material.Neon,
	},
}
