'use strict';

const VERSION = '0.93.0';

const ROOTS = {
  workspace: 'Workspace.CodexProduction.MaterialRealization',
  swatches: 'Workspace.CodexMaterialSwatches',
  replicatedStorage: 'ReplicatedStorage.CodexMaterialProfiles',
  premiumMirror: 'ReplicatedStorage.CodexPremiumDirector.Materials',
  executionMirror: 'ReplicatedStorage.CodexExecutionKernel.Materials',
  lightingProfiles: 'Lighting.CodexLightingProfiles',
};

const CAPABILITIES = [
  'materialPalettes',
  'robloxBuiltInMaterials',
  'colorPaletteApplication',
  'materialSwatchBoards',
  'lightFixturePlanning',
  'glowAccentPlanning',
  'atmosphereProfilePlanning',
  'mobileLightBudget',
  'surfaceAppearanceManualSpecs',
  'executionKernelBridge',
  'detailIntegration',
  'architectureIntegration',
  'fidelityIntegration',
];

const SAFETY = {
  codexOwnedOnly: true,
  manualRequiredForTextureIds: true,
  manualRequiredForSurfaceAppearanceAssets: true,
  globalLightingManualRequiredByDefault: true,
  executionRequiresV72: true,
  noPublishUploadMarketplaceDataStoreEconomy: true,
  noFakeTextureIds: true,
  noFakePbrMaps: true,
};

const AUDIT_KEYS = [
  'paletteCoherence',
  'materialDiscipline',
  'trimContrast',
  'glowDiscipline',
  'lightingDepth',
  'atmosphereClarity',
  'mobileLightSafety',
  'surfaceAppearanceReadiness',
  'premiumMaterialFeel',
  'referenceMoodSupport',
];

const POLISH_STAGES = [
  'improve base/accent contrast',
  'apply material roles',
  'improve trim material contrast',
  'discipline glow/neon',
  'add light fixtures',
  'improve portal glow',
  'add atmosphere profile manifest',
  'reduce mobile light count',
  'rerun visual/fidelity/QA',
];

function nowIso() {
  return new Date().toISOString();
}

function safeGoal(goal) {
  return String(goal || '').trim().replace(/\s+/g, ' ') || 'premium Roblox material pass';
}

function slugify(value, fallback = 'materials') {
  const slug = safeGoal(value)
    .replace(/[^0-9A-Za-z]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 58);
  return slug || fallback;
}

function vec3(x, y, z) {
  return { x, y, z };
}

function color(r, g, b) {
  return { r, g, b };
}

function baseAttributes(role, goal, extra = {}) {
  return {
    CodexGenerated: true,
    CodexSystem: 'MaterialRealization',
    CodexVersion: VERSION,
    CodexGoal: safeGoal(goal),
    CodexMaterialRole: role || 'material',
    ...extra,
  };
}

function materialBasePath(goal, suffix = 'Preview') {
  return `${ROOTS.workspace}.${slugify(goal, 'materials')}_${suffix}`;
}

function materialManifestPath(goal, suffix = 'Preview') {
  return `${ROOTS.replicatedStorage}.${slugify(goal, 'materials')}_${suffix}.MaterialManifestJson`;
}

function operation(op, className, path, role, properties = {}, context = {}) {
  const goal = context.goal || '';
  return {
    op,
    type: op === 'ensureFolder' || className === 'Folder' ? 'folder'
      : op === 'createModel' || className === 'Model' ? 'model'
        : className === 'Part' || className === 'MeshPart' ? 'part'
          : 'createInstance',
    className,
    path,
    role,
    reason: context.reason || `${role} generated by V93 Material Realization.`,
    properties,
    attributes: baseAttributes(role, goal, context.attributes || {}),
    rollback: { action: 'deleteIfCodexGenerated', path },
    verify: { action: 'existsWithAttributes', path, attributes: { CodexGenerated: true, CodexSystem: 'MaterialRealization' } },
    budgetCost: context.budgetCost || 1,
    version: VERSION,
  };
}

function folder(path, role, context = {}) {
  return operation('ensureFolder', 'Folder', path, role || 'folder', {}, { ...context, budgetCost: 0 });
}

function model(path, role, context = {}) {
  return operation('createModel', 'Model', path, role || 'model', {}, { ...context, budgetCost: 0 });
}

function part(path, role, properties = {}, context = {}) {
  return operation('createPart', 'Part', path, role, {
    Anchored: true,
    CanCollide: properties.CanCollide ?? false,
    Transparency: properties.Transparency ?? 0,
    Material: properties.Material || 'SmoothPlastic',
    Color: properties.Color || color(0.2, 0.18, 0.26),
    Size: properties.Size || vec3(4, 1, 4),
    ...properties,
  }, context);
}

function light(path, role, className = 'PointLight', properties = {}, context = {}) {
  return operation('createLight', className, path, role, {
    Brightness: properties.Brightness ?? 1.2,
    Range: properties.Range ?? 16,
    Color: properties.Color || color(0.55, 0.2, 1),
    Shadows: properties.Shadows ?? true,
    ...properties,
  }, { ...context, budgetCost: context.budgetCost || 2 });
}

function stringValue(path, role, value, context = {}) {
  return operation('createManifestValue', 'StringValue', path, role, {
    Value: String(value == null ? '' : value).slice(0, 199000),
  }, { ...context, budgetCost: 0 });
}

module.exports = {
  AUDIT_KEYS,
  CAPABILITIES,
  POLISH_STAGES,
  ROOTS,
  SAFETY,
  VERSION,
  baseAttributes,
  color,
  folder,
  light,
  materialBasePath,
  materialManifestPath,
  model,
  nowIso,
  operation,
  part,
  safeGoal,
  slugify,
  stringValue,
  vec3,
};
