-- Codex Studio Bridge V75 modular source entrypoint.
-- Final bundled output is generated into plugin/CodexStudioBridge.plugin.lua.
-- Edit plugin/src files, then run tools\bridge.cmd plugin bundle.
--#include "legacy/CodexStudioBridge.legacy.lua"
